apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: carshowfinder
type: Opaque
stringData:
  MONGODB_URL: "mongodb://mongodb:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: carshowfinder
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: carshowfinder
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mongodb
          image: mongo:8.2
          ports:
            - containerPort: 27017
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
              add: ["CHOWN", "SETUID", "SETGID", "DAC_OVERRIDE", "FOWNER"]
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: tmp
              mountPath: /tmp
            - name: run
              mountPath: /var/run
      volumes:
        - name: tmp
          emptyDir: {}
        - name: run
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
