apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: carshowfinder
type: Opaque
stringData:
  POSTGRES_PASSWORD: "Ch@ngeMe2026!"
  DATABASE_URL: "postgresql+asyncpg://carshow:Ch@ngeMe2026!@postgres:5432/carshowdb"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: carshowfinder
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: carshowfinder
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: carshowdb
            - name: POSTGRES_USER
              value: carshow
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
